-- The authoritative PostgreSQL schema is maintained as a versioned Flyway
-- migration at src/main/resources/db/migration/V1__initial_schema.sql.
-- Apply it with the postgres Spring profile; do not use Hibernate DDL update
-- against production databases.
